### ISSUE TITLE
anaconda-verify complains about "path" entry for "source"

### ISSUE THREAD

**Issue by mstimberg** [ContinuumIO/anaconda-verify#1]
When using a `meta.yaml` with a "source from a local path" as described at http://conda.pydata.org/docs/building/meta-yaml.html#source-from-a-local-path , `anaconda-verify` complains about

```
RecipeError: in section 'source': unknown key 'path'
```

If `anaconda-verify` is only meant to be used for recipes that live separately from the source code (and therefore use URLs), this should be stated somewhere.

**Comment by mstimberg** [comment]
Um, it also complains about "script" in the "build" section (http://conda.pydata.org/docs/building/meta-yaml.html#script) -- maybe I misunderstood the use of this tool?

**Comment by ilanschnell** [comment]
Yes, in when we build packages for the Anaconda distribution, we always have the recipe separate from the source of the package, which is why the `source/path` field is not allowed.

We also always use explicit `build.sh` and `bld.bat` files, which is why `build/script` is not allowed.

The use and purpose of this tool is better explained here:
https://www.continuum.io/blog/developer-blog/verifying-conda-recipes-and-packages-anaconda-verify

**Comment by ilanschnell** [comment]
In version 1.2.0, which I just released, a --pedantic option was added. Without this option (by default), having the `source/path` section is fine.
